FROM node:13.1-alpine as build
WORKDIR /usr/app
COPY . ./
RUN npm i
RUN npm run tsc 

FROM node:13.1-alpine
LABEL maintainer="Carlos Thurber B."
ENV NODE_ENV production
EXPOSE 3000
WORKDIR /usr/app
COPY --from=build /usr/app/dist ./dist
COPY --from=build /usr/app/node_modules ./node_modules
CMD ["node", "./dist/app.js"]
